GET http://localhost:3000/ HTTP/1.1

### 

POST  https://kgyd56sjra3zpbj2mlhcirpvaa0xrcit.lambda-url.us-east-2.on.aws/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}